name: 🛠️ build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Check-out code
        uses: actions/checkout@v4

      - name: 📐 Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json

      - name: 🔍 Enable problem matchers
        run: echo "::add-matcher::.github/matchers/dotnet.json"

      - name: 🛠️ Build code
        run: dotnet build --configuration Release

  build:
    name: 🛠️ Build
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: 🛒 Check-out code
        uses: actions/checkout@v4

      - name: 📐 Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json

      - name: 🔍 Enable problem matchers
        run: echo "::add-matcher::.github/matchers/dotnet.json"

      - name: 🔧 Load packages
        run: dotnet restore

      - name: 🛠️ Build code
        run: dotnet build --configuration Release -p:Version=${{ github.ref_name }} -p:GitSha=${{ github.sha }} --no-restore

      - name: 📝 Generate Release Notes
        run: gh release create ${{ github.ref_name }} --draft --generate-notes nugets/*.nupkg
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
